<!doctype html>
<html class="no-js" lang="es">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>Contacts</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
		
        <link rel="stylesheet" href="css/normalize.css">
        <link rel="stylesheet" href="css/main.css">
		
		
		<!-- The line below must be kept intact for Sencha Cmd to build your application -->
		<script id="microloader" data-app="3402147b-b865-47a9-9f29-4508933ab16b" type="text/javascript" src="bootstrap.js"></script>
		
    </head>
    <body>
        <!-- Add your site or application content here -->
        <?php echo $this->layout()->content; ?>
    </body>
</html>



